### ISSUE TITLE
cannot connect to Hiro(real robot)

### ISSUE THREAD

**Issue by ghost** [start-jsk/rtmros_hironx#392]
I'm trying to run hironx_ros_bridge and connect to Hiro, but I got following errors.

My enviroment is Ubuntu14.04.3 and indigo.

``````

```~/c/s/l/src ❯❯❯ roslaunch hironx_ros_bridge hironx_ros_bridge_real.launch nameserver:=hiro
... logging to /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/roslaunch-kodai-MacBookPro-13105.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kodai-MacBookPro:34680/

SUMMARY
========

PARAMETERS
 * /HrpsysSeqStateROSBridge/publish_sensor_transforms: True
 * /collision_state/comp_name: CollisionDetector0
 * /controller_configuration: [{'group_name': '...
 * /diagnostic_aggregator/analyzers/computers/contains: ['HD Temp', 'CPU ...
 * /diagnostic_aggregator/analyzers/computers/path: Computers
 * /diagnostic_aggregator/analyzers/computers/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/hrpsys/contains: ['hrpEC']
 * /diagnostic_aggregator/analyzers/hrpsys/path: Hrpsys
 * /diagnostic_aggregator/analyzers/hrpsys/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/mode/contains: ['Operating Mode'...
 * /diagnostic_aggregator/analyzers/mode/path: Mode
 * /diagnostic_aggregator/analyzers/mode/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/motor/contains: ['Motor']
 * /diagnostic_aggregator/analyzers/motor/path: Motor
 * /diagnostic_aggregator/analyzers/motor/type: diagnostic_aggreg...
 * /diagnostic_aggregator/base_path: 
 * /diagnostic_aggregator/pub_rate: 1.0
 * /robot_description: <?xml version="1....
 * /robot_pose_ekf/debug: False
 * /robot_pose_ekf/freq: 30.0
 * /robot_pose_ekf/imu_used: False
 * /robot_pose_ekf/odom_used: True
 * /robot_pose_ekf/output_frame: odom
 * /robot_pose_ekf/self_diagnose: False
 * /robot_pose_ekf/sensor_timeout: 1.0
 * /robot_pose_ekf/vo_used: False
 * /rosdistro: indigo
 * /rosversion: 1.11.13

NODES
  /
    CollisionDetectorComp (hrpsys/CollisionDetectorComp)
    DataLoggerServiceROSBridge (hrpsys_ros_bridge/DataLoggerServiceROSBridgeComp)
    ForwardKinematicsServiceROSBridge (hrpsys_ros_bridge/ForwardKinematicsServiceROSBridgeComp)
    HrpsysJointTrajectoryBridge (hrpsys_ros_bridge/HrpsysJointTrajectoryBridge)
    HrpsysSeqStateROSBridge (hrpsys_ros_bridge/HrpsysSeqStateROSBridge)
    RobotHardwareServiceROSBridge (hrpsys_ros_bridge/RobotHardwareServiceROSBridgeComp)
    SequencePlayerServiceROSBridge (hrpsys_ros_bridge/SequencePlayerServiceROSBridgeComp)
    ServoControllerServiceROSBridge (hrpsys_ros_bridge/ServoControllerServiceROSBridgeComp)
    StateHolderServiceROSBridge (hrpsys_ros_bridge/StateHolderServiceROSBridgeComp)
    base_footprint_rootlink (tf/static_transform_publisher)
    collision_state (hrpsys_ros_bridge/collision_state.py)
    diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
    hrpsys_profile (hrpsys_ros_bridge/hrpsys_profile.py)
    hrpsys_py (hironx_ros_bridge/hironx.py)
    hrpsys_ros_diagnostics (hrpsys_ros_bridge/diagnostics.py)
    hrpsys_state_publisher (robot_state_publisher/state_publisher)
    robot_pose_ekf (robot_pose_ekf/robot_pose_ekf)
    rtmlaunch_collision_detector (openrtm_tools/rtmlaunch.py)
    rtmlaunch_hrpsys_ros_bridge (openrtm_tools/rtmlaunch.py)
    sensor_ros_bridge_connect (hrpsys_ros_bridge/sensor_ros_bridge_connect.py)

WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtconnect
WARNING: unrecognized tag rtactivate
auto-starting new master
process[master]: started with pid [13117]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 888335a0-4d67-11e5-a820-00904c0df43e
process[rosout-1]: started with pid [13130]
started core service [/rosout]
process[hrpsys_py-2]: started with pid [13147]
process[HrpsysSeqStateROSBridge-3]: started with pid [13148]
process[HrpsysJointTrajectoryBridge-4]: started with pid [13150]
process[hrpsys_state_publisher-5]: started with pid [13152]
process[hrpsys_ros_diagnostics-6]: started with pid [13162]
process[diagnostic_aggregator-7]: started with pid [13168]
process[hrpsys_profile-8]: started with pid [13178]
process[sensor_ros_bridge_connect-9]: started with pid [13223]
process[rtmlaunch_hrpsys_ros_bridge-10]: started with pid [13242]
process[SequencePlayerServiceROSBridge-11]: started with pid [13253]
/opt/ros/indigo/share/hrpsys_ros_bridge/scripts/diagnostics.py:75: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub = rospy.Publisher('diagnostics', DiagnosticArray)
process[DataLoggerServiceROSBridge-12]: started with pid [13299]
process[ForwardKinematicsServiceROSBridge-13]: started with pid [13324]
[ERROR] Connection Failed with the Nameserver (hostname=hiro port=15005).
Make sure the hostname is correct and the Nameserver is running.
CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
process[StateHolderServiceROSBridge-14]: started with pid [13334]
[sensor_ros_bridge_connect.py]  start
configuration ORB with hiro:15005
configuration ORB with hiro:15005
process[RobotHardwareServiceROSBridge-15]: started with pid [13339]
[rtmlaunch] starting... [ERROR] Connection Failed with the Nameserver (hostname=hiro port=15005).
Make sure the hostname is correct and the Nameserver is running.
CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
 /opt/ros/indigo/share/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
[rtmlaunch] RTCTREE_NAMESERVERS hiro:15005 hiro:15005
[rtmlaunch] SIMULATOR_NAME RobotHardware0
process[ServoControllerServiceROSBridge-16]: started with pid [13360]
[ERROR] Connection Failed with the Nameserver (hostname=hiro port=15005).
Make sure the hostname is correct and the Nameserver is running.
CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
process[robot_pose_ekf-17]: started with pid [13376]
[hrpsys_profile-8] process has died [pid 13178, exit code 1, cmd /opt/ros/indigo/share/hrpsys_ros_bridge/scripts/hrpsys_profile.py -ORBInitRef NameService=corbaloc:iiop:hiro:15005/NameService __name:=hrpsys_profile __log:=/home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/hrpsys_profile-8.log].
log file: /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/hrpsys_profile-8*.log
[sensor_ros_bridge_connect-9] process has died [pid 13223, exit code 1, cmd /opt/ros/indigo/share/hrpsys_ros_bridge/scripts/sensor_ros_bridge_connect.py /opt/jsk/etc/HIRONX/model/main.wrl RobotHardware0 HrpsysSeqStateROSBridge0 hiro -ORBInitRef NameService=corbaloc:iiop:hiro:15005/NameService __name:=sensor_ros_bridge_connect __log:=/home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/sensor_ros_bridge_connect-9.log].
log file: /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/sensor_ros_bridge_connect-9*.log
Traceback (most recent call last):
  File "/opt/ros/indigo/share/openrtm_tools/scripts/rtmlaunch.py", line 13, in <module>
    rtmlaunch.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/openrtm_tools/rtmlaunch.py", line 225, in main
    tree = rtctree.tree.RTCTree()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 102, in __init__
    self.load_servers_from_env(filter=filter, dynamic=dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 227, in load_servers_from_env
    self._parse_name_servers(servers, filter, dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 279, in _parse_name_servers
    self._parse_name_server(server, filter, dynamic=dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 285, in _parse_name_server
    trim_filter(deepcopy(filter), 2), dynamic=dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/nameserver.py", line 54, in __init__
    self._parse_server(address, orb, filter)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/nameserver.py", line 78, in _parse_server
    root_context = self._connect_to_naming_service(address)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/nameserver.py", line 93, in _connect_to_naming_service
    raise InvalidServiceError(address)
rtctree.exceptions.InvalidServiceError: Invalid CORBA naming service: hiro:15005
process[base_footprint_rootlink-18]: started with pid [13384]
process[CollisionDetectorComp-19]: started with pid [13409]
[rtmlaunch_hrpsys_ros_bridge-10] process has died [pid 13242, exit code 1, cmd /opt/ros/indigo/share/openrtm_tools/scripts/rtmlaunch.py /opt/ros/indigo/share/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch USE_COMMON=true USE_WALKING=false USE_COLLISIONCHECK=false USE_IMPEDANCECONTROLLER=false USE_SOFTERRORLIMIT=false USE_IMAGESENSOR=false USE_ROBOTHARDWARE=true USE_GRASPCONTROLLER=false USE_SERVOCONTROLLER=true USE_TORQUECONTROLLER=false USE_TORQUEFILTER=false __name:=rtmlaunch_hrpsys_ros_bridge __log:=/home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/rtmlaunch_hrpsys_ros_bridge-10.log].
log file: /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/rtmlaunch_hrpsys_ros_bridge-10*.log
process[rtmlaunch_collision_detector-20]: started with pid [13450]
process[collision_state-21]: started with pid [13494]
[ INFO] [1440754278.381082579]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0
;;
;; Could not open /dev/console for writing.
;;
open: Permission denied
terminate called after throwing an instance of 'CORBA::BAD_PARAM'
[hrpsys_py-2] process has died [pid 13147, exit code 1, cmd /opt/ros/indigo/share/hironx_ros_bridge/scripts/hironx.py --host hiro --port 15005 --modelfile /opt/jsk/etc/HIRONX/model/main.wrl --robot RobotHardware __name:=hrpsys_py __log:=/home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/hrpsys_py-2.log].
log file: /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/hrpsys_py-2*.log
[rtmlaunch] starting...  /opt/ros/indigo/share/hrpsys_ros_bridge/launch/collision_detector.launch
[rtmlaunch] RTCTREE_NAMESERVERS hiro:15005 hiro:15005
[rtmlaunch] SIMULATOR_NAME RobotHardware0
Traceback (most recent call last):
  File "/opt/ros/indigo/share/openrtm_tools/scripts/rtmlaunch.py", line 13, in <module>
    rtmlaunch.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/openrtm_tools/rtmlaunch.py", line 225, in main
    tree = rtctree.tree.RTCTree()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 102, in __init__
    self.load_servers_from_env(filter=filter, dynamic=dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 227, in load_servers_from_env
    self._parse_name_servers(servers, filter, dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 279, in _parse_name_servers
    self._parse_name_server(server, filter, dynamic=dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/tree.py", line 285, in _parse_name_server
    trim_filter(deepcopy(filter), 2), dynamic=dynamic)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/nameserver.py", line 54, in __init__
    self._parse_server(address, orb, filter)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/nameserver.py", line 78, in _parse_server
    root_context = self._connect_to_naming_service(address)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rtctree/nameserver.py", line 93, in _connect_to_naming_service
    raise InvalidServiceError(address)
rtctree.exceptions.InvalidServiceError: Invalid CORBA naming service: hiro:15005
[CollisionDetectorComp-19] process has died [pid 13409, exit code -6, cmd /opt/ros/indigo/lib/hrpsys/CollisionDetectorComp -o corba.nameservers:hiro:15005 -o naming.formats:%n.rtc -o exec_cxt.periodic.type:PeriodicExecutionContext -o exec_cxt.periodic.rate:2000 -o logger.file_name:/tmp/collision_detector%p.log -o example.CollisionDetector.config_file:/opt/ros/indigo/share/hironx_ros_bridge/conf/hironx_realrobot_fixedpath.conf __name:=CollisionDetectorComp __log:=/home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/CollisionDetectorComp-19.log].
log file: /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/CollisionDetectorComp-19*.log
[rtmlaunch_collision_detector-20] process has died [pid 13450, exit code 1, cmd /opt/ros/indigo/share/openrtm_tools/scripts/rtmlaunch.py /opt/ros/indigo/share/hrpsys_ros_bridge/launch/collision_detector.launch __name:=rtmlaunch_collision_detector __log:=/home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/rtmlaunch_collision_detector-20.log].
log file: /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/rtmlaunch_collision_detector-20*.log
/opt/ros/indigo/share/hrpsys_ros_bridge/scripts/collision_state.py:181: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub_diagnostics = rospy.Publisher('diagnostics', DiagnosticArray)
/opt/ros/indigo/share/hrpsys_ros_bridge/scripts/collision_state.py:182: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub_collision = rospy.Publisher('collision_detector_marker_array', MarkerArray)
configuration ORB with hiro:15005
[ERROR] Connection Failed with the Nameserver (hostname=hiro port=15005).
Make sure the hostname is correct and the Nameserver is running.
CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
[collision_state-21] process has died [pid 13494, exit code 1, cmd /opt/ros/indigo/share/hrpsys_ros_bridge/scripts/collision_state.py /opt/jsk/etc/HIRONX/model/main.wrl -ORBInitRef NameService=corbaloc:iiop:hiro:15005/NameService __name:=collision_state __log:=/home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/collision_state-21.log].
log file: /home/kodai/.ros/log/888335a0-4d67-11e5-a820-00904c0df43e/collision_state-21*.log
[HrpsysSeqState
``````

**Comment by 130s** [comment]
Can you tell us the output of the following command?

```
rosrun rtshell rtls hiro:15005/
```

Also appreciable is to send the tarball of the following command to support@opensource-robotics.tokyo.jp (no body text is fine; Just refer to this ticket). Thank you.

```
curl -sL https://raw.githubusercontent.com/start-jsk/rtmros_common/master/hrpsys_tools/scripts/rtmroswtf.sh | bash -
```

**Comment by ghost** [comment]
thank for your reply, but I could resolve the problem.

I just forgot to set hiro's host name on /etc/hosts.

**Comment by 130s** [comment]
:)
