### ISSUE TITLE
rqt dashboard crashes when connecting to the real robot

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#429]
UPDATE) See https://github.com/start-jsk/rtmros_hironx/issues/429#issuecomment-180252252 for the error output.

---

<s>

```
[ERROR] [WallTime: 1454388522.232706] bad callback: <bound method ConsoleDashWidget._message_cb of <rqt_robot_dashboard.console_dash_widget.ConsoleDashWidget object at 0x7f81bd774b00>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rqt_robot_dashboard/console_dash_widget.py", line 120, in _message_cb
    if not self._console._paused:
AttributeError: 'NoneType' object has no attribute '_paused'
```

</s>
I guess the dashboard needs `--host` argument when connecting to the real robot.

**Comment by 130s** [comment]
Invalid -- The error output in OP seems not relevant to the hironxo rqt dashboard

**Comment by 130s** [comment]
Ok, here's a true-negative error output.

```
$ rqt &
[1] 8447
[http://roshost:11311][10.254.21.130] rosuser@rosthinkpad:~$ configuration ORB with tork-kudu1:15005
[ERROR] Connection Failed with the Nameserver (hostname=rosthinkpad port=15005).
Make sure the hostname is correct and the Nameserver is running.
CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
```

The error occurs because [HrpsysConfigurator is instantiated without nameserver's host name and port specified](https://github.com/start-jsk/rtmros_hironx/pull/420/files#diff-ee45a856b5ff75ee78f4aefcc4201cb4R73).

**Comment by 130s** [comment]
Opened #438 to fix this.

This issue could also be (more easily than #438) partially resolved by NOT using RTM commands (goInitial, goOffpose) but instead relying on ROS/MoveIt! methods. But there are still methods that are not realized in ROS (checkEncoders, impedance).
